### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by DeastinY** [open-nomie/nomie6-oss#14]
If I want to host thist for my household - is there any user handling in nomie6-oss or was that done externally?

**Comment by ZL1LAC** [comment]
From what I understand each browser is it's own instance of what you have hosted, so you can host it within your house and each person will have there own data on there device or computer.

**Comment by DeastinY** [comment]
true, should have clarifier: want to use the DB backend :)

**Comment by ZL1LAC** [comment]
Each user could have there own DB with user and login using couchDB.

**Comment by thrdroom** [comment]
> Each user could have there own DB with user and login using couchDB.

just to clear this up. does this mean that one couchdb container does only hold a single db for one user?
does one have to spin up multiple couchdb docker containers for multiple users?
or can you run a single couchdb docker container that can host multiple dbs for multiple users in one container?

**Comment by DeastinY** [comment]
While not super userfriendly I guess this will have to do for now :)
