### ISSUE TITLE
Add an option to disable achievements

### ISSUE THREAD

**Issue by allo-** [open-nomie/nomie6-oss#18]
When I first tried Nomie 6, it told me I can only add persons after I got the achievement to having used Nomie 6 for one day.

While achievements may be a nice incentive to try more features for some people, they are an annoyance when one just wants to use the app. And it's especially annoying when some features are not available from the start.

So I would suggest to add a setting to disable them, or at least disable them as precondition for using certain features.

**Comment by thrdroom** [comment]
I wouldn't want to disable achievements completely but at least remove all app feature restrictions for new users.

**Comment by allo-** [comment]
I think don't care too much about them being there or not, but especially when I already used Nomie before, I would like to start directly. I think it even wanted me to wait one day when I imported two years of data and then add another person tracker.  
I guess an additional switch to disable them completely somewhere in "advanced settings" wouldn't be too complicated either.
