### ISSUE TITLE
Image compression is too aggressive

### ISSUE THREAD

**Issue by thrdroom** [open-nomie/nomie6-oss#23]
**Bug description:**
When i add images to people or other objects in nomie, the pictures get compressed so aggressively that it renders the pictures unrecognisable. The results are mostly pixel mash (screenshot below). In this state this feature is unusable.

**Expected behaviour:**
Do compress images, but less aggressive, and in a higher resolution. The user should at least recognize the faces of the person in the pictures.

![image](https://user-images.githubusercontent.com/5912061/212077235-f987bf80-9a07-418b-9e6d-caed0b07c7e9.png)

**Comment by donalmacanri** [comment]
More info:

I think the culprit might be line line 39 in src/components/uploader/image-uploader.svelte. The image is scaled to 64*64 pixels with a high compression ratio and stored as a data URL. I would guess there was a specific reason for this ... perhaps a limitations in one of Nomie's storage backends. Need to tinker with it and test.

**Comment by brandoncorbin** [comment]
As @donalmacanri pointed out, since all image assets are stored as base64 strings in the storage engine, we need them to be small as possible. Maybe going with a base64 of the webp format could lead to better results.

**Comment by donalmacanri** [comment]
I did a couple of tests with some stock photos of people. As you suggested, webp produces better results - slightly smaller images (10-20%), and subjectively, they look a bit better to me.  However, they were still really pixelated. Even with the quality bumped up to 100%, they lost too much detail at 64*64.

Increasing the max width and height by a factor of 4 seemed to be the sweet spot to me. However, the data URLs are bigger as well. Still generally under 1 KB though, and no noticeable impact on performance, but I'm maybe I'm not looking in the right places. @brandoncorbin do you think 1KB data URLs for images would be ok?
