### ISSUE TITLE
Active tracking board doesn't load

### ISSUE THREAD

**Issue by donalmacanri** [open-nomie/nomie6-oss#29]
From @Robin-Sch in meta-issue #25 :

> When I open nomie on my phone, the tracking tab doesn't load. When I click on another tab it does load, and when I go back to the first tab that one also does load.

> Actually, it only doesn't load on the second tab. If I select the first tab, close nomie, then open it again it does load. But when I select the second tab, close nomie, then open it again then it doesn't load.

> I also added a third tab, and that one doesn't load either. Only the first tab loads correctly, and the others don't.

> If I press edit, and switch the tabs around, it still doesn't load the second or third tab (even the one which did load before). The only tab that loads is the one which is the first tab.

> So like, I have 3 tabs: 1, 2 and 3.
> The order: 1, 2, 3, then tab 1 loads, and 2 and 3 don't
> The order: 2, 3, 1, then tab 2 loads, and 3 and 1 don't
> The order: 3, 1, 2, then tab 3 loads, and 1 and 2 don't

**Comment by c-rohrbach** [comment]
I think I found another case of this:
When you start a fresh instance and install a starter template from the initial setup, the board also is not loaded when you finish the setup.
