### ISSUE TITLE
Discussion: nomie-plugin.js -how to make available-

### ISSUE THREAD

**Issue by RdeLange** [open-nomie/nomie6-oss#3]
Question: how do we want to deal with the **_nomie-plugin.js_** file.
Do we want to make it available for download so that it can be directly included in the plugin source code?

**Comment by ZL1LAC** [comment]
Could plugins be hosted on GitHub pages?

**Comment by RdeLange** [comment]
Sure, every plugin which is not depending on server processes but which can run independently (as Nomie) should be able to be deployed on Github pages. I am currently busy finalizing a plugin. Once done I will try to deploy it on Github pages.

**Comment by RdeLange** [comment]
@ZL1LAC and there we go. I have tested it on my forked repo. For example the meditate plugin can now be installed via: https://rdelange.github.io/v1/plugins/meditate/

**Comment by ZL1LAC** [comment]
Yup, I think that's a pretty good approach to plugins.

**Comment by RdeLange** [comment]
Closed as this is now solved with a new update on the repo open-nomie/plugins
