### ISSUE TITLE
The note input field get empty when you navigate throgh menu

### ISSUE THREAD

**Issue by edil-it-them** [open-nomie/nomie6-oss#37]
When I make notes and navigate through menu, for example clicking on Timeline, Dashboard, Goals, Track, etc the input note disappears until you click on it.
Steps to reproduce:
1) make a note, click on a tracker
2) click on any menu navigation tab
3) click again on note input(What's up field)

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/44370635/214450462-407f3c55-18ac-49ad-af1a-dc8a4926bfd1.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/44370635/214450491-1d1a435e-638d-4010-9cf3-d5c4a30a85da.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/44370635/214450526-ac483189-2b71-4d1c-a718-582720cbc96f.png">

Expected behavior:
The note should stay visible as it is

**Comment by donalmacanri** [comment]
Interesting ... this is not really a problem on mobile because you can't navigate between Track, Timeline, Dashboard, etc. without either saving or cancelling. I think on Desktop, we either need to let the note stay visible as you suggest, or give the user a warning if they are navigating to a different tab and confirm to proceed.

**Comment by Rolikasi** [comment]
Sometimes I need to navigate to dashboards, trackers and timeline when I journal so I can view previous inputs or charts. 
So I'd love to keep it visible. The problem might be when the input textfield component is created. 
The note text probably is stored in stores but the component initializes empty string on text field. But when you focus on it its bringing value from the store. Didn't yet looked in the codebase but the solution might be just simple
`let inputText = $ActiveLogStore.note || ''`

**Comment by edil-it-them** [comment]
Closed via #44
