### ISSUE TITLE
Docker availablity

### ISSUE THREAD

**Issue by qcasey** [open-nomie/nomie6-oss#5]
Thank you for open sourcing nomie6! I'm terribly sorry this didn't work out as a business, but you're helping a tremendous number of people by releasing it to the public.

Are there any plans for a `Dockerfile` and uploading to docker hub / ghcr? If not, are you accepting PRs for this? I think it would help in self-hosting.

**Comment by donalmacanri** [comment]
A PR for this would be great! I was planning to add a docker-compose configuration to support self-hosting with a CouchDB server for storage as well.

**Comment by qcasey** [comment]
Excellent, I'll draft that PR now. Adding a CouchDB server is a great idea
