### ISSUE TITLE
[bug] dashboard timeframes (last week, last 7 days) don't work as expected: 

### ISSUE THREAD

**Issue by lukaszstr** [open-nomie/nomie6-oss#58]
- [ ] Timeframe `Last 7 days` shows 8 days:
![image](https://user-images.githubusercontent.com/12358553/222156151-2b4686d5-5cc5-4854-9665-f380d94a402e.png)
- [ ] If setting `Week Starts` is set to: `Monday` dashboard widget with timeframe: `Last Week` **doesn't include** the last day (Sunday)
![image](https://user-images.githubusercontent.com/12358553/222161208-04503fdb-4e10-4d16-8f57-4e7ebfc580c2.png)
(There is an event "gymnastic" on 26/2)

Checked on Nomie 6.3.0

**Comment by RdeLange** [comment]
Good catch! I will try to have this recreated and fixed

**Comment by RdeLange** [comment]
@lukaszstr 
Good news, I have been able to identify the first bug and created a fix for it.
With respect to the second issue I am not able to recreate it (yet). I have tested it with my data, but it shows me always the Sunday data in the chart. (also after switching a couple of times between Sunday/Monday week start)
Can you please try again, maybe with some other trackables? Also maybe some info on the device you are running Nomie on (Android/IOS/) or which browser?
Thanks!

**Comment by lukaszstr** [comment]
Thanks @RdeLange Took another look into this.
And this one is tricky indeed. 

I was able to recreate it with new nomie instance - on macos, chromium based browser, created a new tally tracker added some history and a single widget. It reproduced the issue. Now I wanted to add another widget side to it to display last 7 days and this caused the widgets to redraw and issue disappeared.
So if I have on a given `Dashboard` **only** widgets with `Last Week` timeframe I have the issue, when I add any tracker with different timeframe the issue disappears.
I attach sshots, maybe those will display that better:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/12358553/222266508-16378c52-9fa4-4fd5-9ffd-5e791f388e95.png">
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/12358553/222266595-044897d3-955b-443e-95a5-11851a70499e.png">

**So issue is only present when all widgets in the dashboard have "Last Week" timeframe.**


WA: A workaround is to add any widget with different timeframe

**Comment by RdeLange** [comment]
Thanks! I am able to recreate the bug. This is definitely a tricky one. I will dig into it the coming days.

**Comment by RdeLange** [comment]
I was also able to fix the 2nd issue.
I have fixed both in the code and issued a pull request: #59 

Could you check the generated test instance on Netlify as shown in the pull request to validate if this is now working for you?

thanks!

**Comment by lukaszstr** [comment]
Tested with Netlify deployment, both above-mentioned issues are fixed 👍

**Comment by RdeLange** [comment]
Thanks for testing! 
Theses fixes will probably become part of the next release
