### ISSUE TITLE
Not informative TV Shows tracking

### ISSUE THREAD

**Issue by red-avtovo** [open-nomie/nomie6-oss#68]
When I'm watching a TV show and marking my progress by submitting watched episodes, there is no notion of whether I'm watching the TV show right now (nothing on the summary page) or what is the next unwatched episode (no info on tv shows page).
<img width="943" alt="image" src="https://github.com/open-nomie/nomie6-oss/assets/10682826/51f110e9-4210-440b-980b-b8d5a06f7e82">

<img width="1012" alt="image" src="https://github.com/open-nomie/nomie6-oss/assets/10682826/a682bdcc-b88a-4cbf-8ad5-88bb64e2fc37">

On top of that, by opening the show, old seasons are not marked as seen

<img width="1010" alt="image" src="https://github.com/open-nomie/nomie6-oss/assets/10682826/c2d2b088-b8bc-4766-8997-8a1d1a857361">

Even though the history is updated

<img width="604" alt="image" src="https://github.com/open-nomie/nomie6-oss/assets/10682826/7b55d45d-3d93-4ecb-95d5-65d165f4601a">

**Comment by tjquinn1** [comment]
@red-avtovo are you in the right repo?

**Comment by red-avtovo** [comment]
Ha, you're so right. Sorry for the confusion. Probably the wrong issues link was shared with me
