### ISSUE TITLE
Suggestion: hosting a current stable version of the app using GitHub pages

### ISSUE THREAD

**Issue by donalmacanri** [open-nomie/nomie6-oss#8]
It is possible to use GitHub actions to automatically build and publish the code from a branch to GitHub pages (for free). In addition to the self-hosting options, I'm wondering if @brandoncorbin would be ok with the latest stable version existing on GitHub pages as well for less technical users?

**Comment by brandoncorbin** [comment]
I have no problem with a build out there that others can use. My only concern is that it falls on us in the event that something breaks.  However, now that the firebase and encryption madness is pulled from this version, the risk of breaking things / data access, is a lot less.

**Comment by donalmacanri** [comment]
That's a reasonable concern. I'm happy to be responsible for fixing, in the event of breakage.

I'll get a PR up.

**Comment by ZL1LAC** [comment]
So this would be hosted by GitHub itself?  How would that work?

**Comment by donalmacanri** [comment]
GitHub pages is a static hosting service provided by GitHub. It can be tied together with GitHub actions to automatically a build a static site from source and deploy to Github Pages, eg when commits are pushed to a particular branch. It is often used by projects to host documentation, but in this case could be used to host the Nomie app, since all it requires is static file hosting.

**Comment by donalmacanri** [comment]
@brandoncorbin I added you to a repo called open-nomie.github.io. If you accept the invite, I can make you an admin, which should allow you to transfer it to the open-nomie organization. The repo has Github pages enabled as well as an action to build from this repo. As far as I can tell, as long as the open-nomie.github.io repo exists in the open-nomie organization, the Github pages URL for it will be https://open-nomie.github.io/.

(Originally, I tried to set up Github pages and configure the Github action directly on this repo, but then the application would live at open-nomie.github.io/nomie6-oss/, while the app expects to live on the root path and would not work correctly.)

**Comment by brandoncorbin** [comment]
@donalmacanri transfered to open-nomie!

**Comment by ZL1LAC** [comment]
Looking forward to seeing this!

**Comment by brandoncorbin** [comment]
@ZL1LAC looks like it's already running! https://open-nomie-github.io

**Comment by ZL1LAC** [comment]
@brandoncorbin you sure?  Comes back with site not found?

**Comment by brandoncorbin** [comment]
@ZL1LAC  I screwed up the url in that reply... It's actually https://open-nomie.github.io/

**Comment by ZL1LAC** [comment]
Ah ok all good.

**Comment by executive-of-dysfxn** [comment]
One of the less technical users here! I want to see if I'm following this right. Instead of downloading the zip file and adding it somewhere for self-hosting, I could access Open Nomie from https://open-nomie.github.io/, and my data would be stored in my browser? 

I was wondering what would happen if there was ever an update to the version of N6 here, how I'd update my version. I was thinking I'd just have to download a new zip file and import a back up of my data. Would using the GitHub Pages version get around that issue or am I misunderstanding?

**Comment by brandoncorbin** [comment]
@executive-of-dysfxn yes, thats correct you can run it on this domain, and it will all still be stored in your browser. New Updates will get built automatically and deployed to this URL. As long as the new updates are done properly (specifically the package.json version number being increased) Nomie will let you know that there's a new Update with an "Update Available" prompt like before.

**Comment by donalmacanri** [comment]
You got it! Whenever there is an update here, it will get deployed to https://open-nomie.github.io/ and you should get a notification within the app allowing you to update to the latest version, without needing to download and re-import a backup of your data. Your data remains stored in your browser all the while.

**Comment by brandoncorbin** [comment]
@donalmacanri is there anyway to have Github Actions, run a release:patch when a new PR is merged into Master? That way we could always have an updated version number in the package.json without having developers be responsible for it. I've never used Github Actions so I'm flying a bit blind. 

```
"release:patch": "release-it patch --no-npm.publish",
"release:minor": "release-it minor --no-npm.publish",
```

**Comment by donalmacanri** [comment]
I think so ... let me give it a try.

**Comment by donalmacanri** [comment]
work-in-progress, almost there:
https://github.com/open-nomie/nomie6-oss/pull/13

**Comment by donalmacanri** [comment]
@brandoncorbin, [this PR](https://github.com/open-nomie/nomie6-oss/pull/13) should do the job. Apart from merging it, there's a bit of configuration to do with access tokens to make it work. I've added instructions to the PR set up the tokens - let me know in any way.
