### ISSUE TITLE
Option to disable "what's up?" in v6?

### ISSUE THREAD

**Issue by donalmacanri** [open-nomie/nomie6-oss#9]
From Reddit (https://www.reddit.com/r/nomie/comments/zt4war/can_we_disable_whats_up_in_v6/)

I often find that when I want to track multiple events one after another, the "what's up?" prompt captures my device's focus and moves the screen to make room for the keyboard, so I end up tapping on an event I didn't intend to tap. Is it possible to disable that prompt, or at least keep it from forcing the screen to scroll?

**Comment by brandoncorbin** [comment]
So this doesn't happen on iOS, but I am seeing it on Android. The main culprit is on line 26 of `domains/capture-log/capture-textarea.svelte` if you remove the autofocus, it won't bring up the keyboard. However, we'd want to make sure to test it, as I'm not 100% certain what all that might affect.
